name: reminder_lite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 9.3.0+1
  cupertino_icons: 1.0.8
  provider: 6.1.2
  flutter_bloc: 9.1.0
  freezed_annotation: 2.4.4
  progress_circle: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15
  auto_route_generator: 9.3.1
  freezed: 2.5.8
  lakos: 2.0.5



flutter:
  generate: true
  
