name: reminder_lite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 8.3.0
  cupertino_icons: 1.0.8
  provider: 6.1.2
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  freezed_annotation: 2.4.4
  progress_circle: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.14
  auto_route_generator: 8.0.0
  freezed: 2.5.7
  lakos: 2.0.4


flutter:
  generate: true
  
