name: reminder_lite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  go_router: 14.2.0
  cupertino_icons: 1.0.8
  provider: 6.1.2
  flutter_bloc: 8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  build_runner: 2.4.11
  freezed: 2.5.2


flutter:
  generate: true
  
